"""empty message

Revision ID: a5801dfd76b4
Revises: 
Create Date: 2020-02-02 15:31:53.877948

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a5801dfd76b4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('friends_ibfk_1', 'friends', type_='foreignkey')
    op.create_foreign_key(None, 'friends', 'users', ['user_id'], ['id'])
    op.alter_column('users', 'created_on',
               existing_type=mysql.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_on',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.drop_constraint(None, 'friends', type_='foreignkey')
    op.create_foreign_key('friends_ibfk_1', 'friends', 'friends', ['user_id'], ['id'])
    # ### end Alembic commands ###
